In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import date
import matplotlib.pyplot as plt
import regex as re
import os
from pathlib import Path
from data_ext import create_extra_dates, create_extra_data

In [166]:
path_list = [
"C&I_DELNQ_QTR.xlsx",
"CCARD_CO_QTR.xlsx",
'CCARD_DELNQ_QTR.xlsx',
'CORP_DEBT_NET_WORTH_QTR.xlsx',
'CORP_SAVINGS_LEVEL_QTR.xlsx',
'CRE_CO_QTR.xlsx',
'CRE_DELNQ_QTR.xlsx',
'GDP_QTR.xlsx',
'Homeowner_Vacancy_rate_QTR.xlsx',
'Household_DBT_Inc_QTR.xlsx',
'Mortgage_CO_QTR.xlsx',
'Mortgage_DELNQ_QTR.xlsx',
'Rental_Vacancy_Rate_QTR.xlsx']

for file_name in path_list:
    print(Path(f'..\Project-Loan-Charge-Offs\Resources\{file_name}'))
    get_var = ex = re.findall(r"(.*?)_QTR\.xlsx", file_name)
    print(get_var)

..\Project-Loan-Charge-Offs\Resources\C&I_DELNQ_QTR.xlsx
['C&I_DELNQ']
..\Project-Loan-Charge-Offs\Resources\CCARD_CO_QTR.xlsx
['CCARD_CO']
..\Project-Loan-Charge-Offs\Resources\CCARD_DELNQ_QTR.xlsx
['CCARD_DELNQ']
..\Project-Loan-Charge-Offs\Resources\CORP_DEBT_NET_WORTH_QTR.xlsx
['CORP_DEBT_NET_WORTH']
..\Project-Loan-Charge-Offs\Resources\CORP_SAVINGS_LEVEL_QTR.xlsx
['CORP_SAVINGS_LEVEL']
..\Project-Loan-Charge-Offs\Resources\CRE_CO_QTR.xlsx
['CRE_CO']
..\Project-Loan-Charge-Offs\Resources\CRE_DELNQ_QTR.xlsx
['CRE_DELNQ']
..\Project-Loan-Charge-Offs\Resources\GDP_QTR.xlsx
['GDP']
..\Project-Loan-Charge-Offs\Resources\Homeowner_Vacancy_rate_QTR.xlsx
['Homeowner_Vacancy_rate']
..\Project-Loan-Charge-Offs\Resources\Household_DBT_Inc_QTR.xlsx
['Household_DBT_Inc']
..\Project-Loan-Charge-Offs\Resources\Mortgage_CO_QTR.xlsx
['Mortgage_CO']
..\Project-Loan-Charge-Offs\Resources\Mortgage_DELNQ_QTR.xlsx
['Mortgage_DELNQ']
..\Project-Loan-Charge-Offs\Resources\Rental_Vacancy_Rate_QTR.xlsx
['Rental_Vacancy_Rate']

In [165]:
file_ex = path_list[0]
ex = re.findall(r"(.*?)_QTR\.xlsx", file_ex)
print(ex)

['C&I_DELNQ']

In [2]:
## import CORP_DEBT_NET_WORTH_QTR Data
print(os.getcwd())
data = Path('..\Project-Loan-Charge-Offs\Resources\CORP_DEBT_NET_WORTH_QTR.xlsx')
df = pd.read_excel(data, header=10)

## Prepare date data
df["observation_date"] = df["observation_date"].astype("datetime64[M]")
val_col = df.columns[1]
df = df.rename(columns={val_col: "CORP_DEBT_NET_WORTH_QTR"})

c:\Users\guerr\Desktop\Berkeley_Bootcamp_DataAnalysis\Project 4\Project-Loan-Charge-Offs

  observation_date  NCBCMDPNWMV
0       1945-10-01    22.428658

In [7]:
## Originally where data functions were
#  initialize data arrays
date_list = df["observation_date"]
CORP_values = df["CORP_DEBT_NET_WORTH_QTR"]

In [8]:
## Extend Data with UDF
new_datelist = create_extra_dates(date_list)
new_CORP_values = create_extra_data(CORP_values)

## create new Dataframes
new_df = pd.DataFrame({"new_datelist": new_datelist, "new_CORP_values": new_CORP_values})
new_df

    new_datelist  new_CORP_values
0     1945-10-01        22.428658
1     1945-11-01        22.428658
2     1945-12-01        22.428658
3     1946-01-01              NaN
4     1946-02-01              NaN
..           ...              ...
928   2023-02-01        40.497128
929   2023-03-01        40.497128
930   2023-04-01        39.659559
931   2023-05-01        39.659559
932   2023-06-01        39.659559

[933 rows x 2 columns]

In [11]:
## Export df
new_df.to_csv("..\Project-Loan-Charge-Offs\Resources\CORP_DEBT_NET_WORTH_MO.csv", sep=',', encoding='UTF-8')

In [17]:
## IMPORT C&I_DELNQ_QTR
data2 = Path('..\Project-Loan-Charge-Offs\Resources\C&I_DELNQ_QTR.xlsx')
df2 = pd.read_excel(data2, header=10)
df2.head()

## Prepare date data
df2["observation_date"] = df2["observation_date"].astype("datetime64[M]")
val_col2 = df2.columns[1]
df2 = df2.rename(columns={val_col2: "C&I_DELNQ_QTR"})

## Originally where data functions were
#  initialize data arrays
date_list2 = df2["observation_date"]
data_values2 = df2["C&I_DELINQ_QTR"]

## Extend Data with UDF
new_datelist2 = create_extra_dates(date_list2)
newdata_values2 = create_extra_data(data_values2)

## create new Dataframes
new_df2 = pd.DataFrame({"new_datelist": new_datelist2, "new_DELNQ_values": newdata_values2})
new_df2

## Export df
new_df.to_csv("..\Project-Loan-Charge-Offs\Resources\C&I_DELNQ_MO.csv", sep=',', encoding='UTF-8')

In [23]:
## IMPORT CCARD_CO_QTR
data3 = Path('..\Project-Loan-Charge-Offs\Resources\CCARD_CO_QTR.xlsx')
df3 = pd.read_excel(data3, header=10)
df3.head()

## Prepare date data
df3["observation_date"] = df3["observation_date"].astype("datetime64[M]")
val_col3 = df3.columns[1]

#  initialize data arrays
date_list3 = df3["observation_date"]
data_values3 = df3[val_col3]

## Extend Data with UDF
new_datelist3 = create_extra_dates(date_list3)
newdata_values3 = create_extra_data(data_values3)

## create new Dataframes
new_df3 = pd.DataFrame({"new_datelist": new_datelist3, "new_CCARD_CO_values": newdata_values3})
new_df3

## Export df
new_df3.to_csv("..\Project-Loan-Charge-Offs\Resources\CCARD_CO_MO.csv", sep=',', encoding='UTF-8')

    new_datelist  new_CCARD_CO_values
0     1985-01-01                 1.90
1     1985-02-01                 1.90
2     1985-03-01                 1.90
3     1985-04-01                 2.26
4     1985-05-01                 2.26
..           ...                  ...
457   2023-02-01                 2.89
458   2023-03-01                 2.89
459   2023-04-01                 3.15
460   2023-05-01                 3.15
461   2023-06-01                 3.15

[462 rows x 2 columns]

In [ ]:
## IMPORT CCARD_DELNQ_QTR
data4 = Path('..\Project-Loan-Charge-Offs\Resources\CCARD_DELNQ_QTR.xlsx')
df4 = pd.read_excel(data4, header=10)
df4.head()

## Prepare date data
df4["observation_date"] = df4["observation_date"].astype("datetime64[M]")
val_col4 = df4.columns[1]

#  initialize data arrays
date_list4 = df4["observation_date"]
data_values4 = df4[val_col4]

## Extend Data with UDF
new_datelist4 = create_extra_dates(date_list4)
newdata_values4 = create_extra_data(data_values4)

## create new Dataframes
new_df4 = pd.DataFrame({"new_datelist": new_datelist4, "new_CCARD_DELNQ_values": newdata_values4})
new_df4

## Export df
new_df4.to_csv("..\Project-Loan-Charge-Offs\Resources\CCARD_DELNQ_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
## IMPORT CORP_DEBT_NET_WORTH_QTR
data5 = Path('..\Project-Loan-Charge-Offs\Resources\CORP_DEBT_NET_WORTH_QTR.xlsx')
df5 = pd.read_excel(data5, header=10)
df5.head()

## Prepare date data
df5["observation_date"] = df5["observation_date"].astype("datetime64[M]")
val_col5 = df5.columns[1]

#  initialize data arrays
date_list5 = df5["observation_date"]
data_values5 = df5[val_col5]

## Extend Data with UDF
new_datelist5 = create_extra_dates(date_list5)
newdata_values5 = create_extra_data(data_values5)

## create new Dataframes
new_df5 = pd.DataFrame({"new_datelist": new_datelist5, "new_CORP_DEBT_NET_WORTH_values": newdata_values5})
new_df5

## Export df
new_df5.to_csv("..\Project-Loan-Charge-Offs\Resources\CORP_DEBT_NET_WORTH_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT CORP_SAVINGS_LEVEL_QTR
data6 = Path('..\Project-Loan-Charge-Offs\Resources\CORP_SAVINGS_LEVEL_QTR.xlsx')
df6 = pd.read_excel(data6, header=10)
df6.head()

## Prepare date data
df6["observation_date"] = df6["observation_date"].astype("datetime64[M]")
val_col6 = df6.columns[1]

#  initialize data arrays
date_list6 = df6["observation_date"]
data_values6 = df6[val_col6]

## Extend Data with UDF
new_datelist6 = create_extra_dates(date_list6)
newdata_values6 = create_extra_data(data_values6)

## create new Dataframes
new_df6 = pd.DataFrame({"new_datelist": new_datelist6, "new_CORP_SAVINGS_LEVEL_values": newdata_values6})
new_df6

## Export df
new_df6.to_csv("..\Project-Loan-Charge-Offs\Resources\CORP_SAVINGS_LEVEL_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT CRE_CO_QTR
data7 = Path('..\Project-Loan-Charge-Offs\Resources\CRE_CO_QTR.xlsx')
df7 = pd.read_excel(data7, header=10)
df7.head()

## Prepare date data
df7["observation_date"] = df7["observation_date"].astype("datetime64[M]")
val_col7 = df7.columns[1]

#  initialize data arrays
date_list7 = df7["observation_date"]
data_values7 = df7[val_col7]

## Extend Data with UDF
new_datelist7 = create_extra_dates(date_list7)
newdata_values7 = create_extra_data(data_values7)

## create new Dataframes
new_df7 = pd.DataFrame({"new_datelist": new_datelist7, "new_CRE_CO_QTR_values": newdata_values7})
new_df7

## Export df
new_df7.to_csv("..\Project-Loan-Charge-Offs\Resources\CRE_CO_QTR_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT GDP_QTR
data8 = Path('..\Project-Loan-Charge-Offs\Resources\GDP_QTR.xlsx')
df8 = pd.read_excel(data8, header=10)
df8.head()

## Prepare date data
df8["observation_date"] = df8["observation_date"].astype("datetime64[M]")
val_col8 = df8.columns[1]

#  initialize data arrays
date_list8 = df8["observation_date"]
data_values8 = df8[val_col8]

## Extend Data with UDF
new_datelist8 = create_extra_dates(date_list8)
newdata_values8 = create_extra_data(data_values8)

## create new Dataframes
new_df8 = pd.DataFrame({"new_datelist": new_datelist8, "new_GDP_QTR_values": newdata_values8})
new_df8

## Export df
new_df8.to_csv("..\Project-Loan-Charge-Offs\Resources\GDP_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT Homeowner_Vacancy_Rate_QTR
data9 = Path('..\Project-Loan-Charge-Offs\Resources\Homeowner_Vacancy_Rate_QTR.xlsx')
df9 = pd.read_excel(data9, header=10)
df9.head()

## Prepare date data
df9["observation_date"] = df9["observation_date"].astype("datetime64[M]")
val_col9 = df9.columns[1]

#  initialize data arrays
date_list9 = df9["observation_date"]
data_values9 = df9[val_col9]

## Extend Data with UDF
new_datelist9 = create_extra_dates(date_list9)
newdata_values9 = create_extra_data(data_values9)

## create new Dataframes
new_df9 = pd.DataFrame({"new_datelist": new_datelist9, "new_Homeowner_Vacancy_Rate_QTR_values": newdata_values9})
new_df9

## Export df
new_df9.to_csv("..\Project-Loan-Charge-Offs\Resources\Homeowner_Vacancy_Rate_MO.csv", sep=',', encoding='UTF-8')

In [24]:
# IMPORT Household_DBT_Inc_QTR
data10 = Path('..\Project-Loan-Charge-Offs\Resources\Household_DBT_Inc_QTR.xlsx')
df10 = pd.read_excel(data10, header=10)
df10.head()

## Prepare date data
df10["observation_date"] = df10["observation_date"].astype("datetime64[M]")
val_col10 = df10.columns[1]

#  initialize data arrays
date_list10 = df10["observation_date"]
data_values10 = df10[val_col10]

## Extend Data with UDF
new_datelist10 = create_extra_dates(date_list10)
newdata_values10 = create_extra_data(data_values10)

## create new Dataframes
new_df10 = pd.DataFrame({"new_datelist": new_datelist10, "new_Household_DBT_Inc_QTR_values": newdata_values10})
new_df10

## Export df
new_df10.to_csv("..\Project-Loan-Charge-Offs\Resources\Household_DBT_Inc_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT Mortgage_CO_QTR
data11 = Path('..\Project-Loan-Charge-Offs\Resources\Mortgage_CO_QTR.xlsx')
df11 = pd.read_excel(data11, header=10)
df11.head()

## Prepare date data
df11["observation_date"] = df11["observation_date"].astype("datetime64[M]")
val_col11 = df11.columns[1]

#  initialize data arrays
date_list11 = df11["observation_date"]
data_values11 = df11[val_col11]

## Extend Data with UDF
new_datelist11 = create_extra_dates(date_list11)
newdata_values11 = create_extra_data(data_values11)

## create new Dataframes
new_df11 = pd.DataFrame({"new_datelist": new_datelist11, "new_Mortgage_CO_QTR_values": newdata_values11})
new_df11

## Export df
new_df11.to_csv("..\Project-Loan-Charge-Offs\Resources\Mortgage_CO_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT Mortgage_DELNQ_QTR
data12 = Path('..\Project-Loan-Charge-Offs\Resources\Mortgage_DELNQ_QTR.xlsx')
df12 = pd.read_excel(data12, header=10)
df12.head()

## Prepare date data
df12["observation_date"] = df12["observation_date"].astype("datetime64[M]")
val_col12 = df12.columns[1]

#  initialize data arrays
date_list12 = df12["observation_date"]
data_values12 = df12[val_col12]

## Extend Data with UDF
new_datelist12 = create_extra_dates(date_list12)
newdata_values12 = create_extra_data(data_values12)

## create new Dataframes
new_df12 = pd.DataFrame({"new_datelist": new_datelist12, "new_Mortgage_DELNQ_QTR_values": newdata_values12})
new_df12

## Export df
new_df12.to_csv("..\Project-Loan-Charge-Offs\Resources\Mortgage_DELNQ_MO.csv", sep=',', encoding='UTF-8')

In [ ]:
# IMPORT Rental_Vacancy_Rate_QTR
data13 = Path('..\Project-Loan-Charge-Offs\Resources\Rental_Vacancy_Rate_QTR.xlsx')
df13 = pd.read_excel(data13, header=10)
df13.head()

## Prepare date data
df13["observation_date"] = df13["observation_date"].astype("datetime64[M]")
val_col13 = df13.columns[1]

#  initialize data arrays
date_list13 = df13["observation_date"]
data_values13 = df13[val_col13]

## Extend Data with UDF
new_datelist13 = create_extra_dates(date_list13)
newdata_values13 = create_extra_data(data_values13)

## create new Dataframes
new_df13 = pd.DataFrame({"new_datelist": new_datelist13, "new_Rental_Vacancy_Rate_QTR_values": newdata_values13})
new_df13

## Export df
new_df13.to_csv("..\Project-Loan-Charge-Offs\Resources\Rental_Vacancy_Rate_MO.csv", sep=',', encoding='UTF-8')

Need Converting:
C&I_DELNQ_QTR.xlsx
CCARD_CO_QTR.xlsx
CCARD_DELNQ_QTR.xlsx
CORP_DEBT_NET_WORTH_QTR.xlsx
CORP_SAVINGS_LEVEL_QTR.xlsx
CRE_CO_QTR.xlsx
CRE_DELNQ_QTR.xlsx
GDP_QTR.xlsx
Homeowner_Vacancy_rate_QTR.xlsx
Household_DBT_Inc_QTR.xlsx
Mortgage_CO_QTR.xlsx
Mortgage_DELNQ_QTR.xlsx
Rental_Vacancy_Rate_QTR.xlsx

Already done:
C&I_CO_QTR.xlsx

Requires diff method:
Consumer_Confidence_MO.xlsx
FEDFUNDS_MO.xlsx
Manufacturing_Confidence_MO.xlsx
SAVINGS_RATE_MO.xlsx
UNRATE_MONTHLY.xlsx